<?php
return [
    'modules' => [
        'HOME' => 'home',
        'SITEMAP' => 'sitemap',
        'EDIT_PROFILE' => 'edit_profile',
        'CHANGE_PASSWORD' => 'change_password',
        'DASHBOARD' => 'dashboard',
        'USER_MANAGEMENT' => 'user_management',
        'ADMIN' => 'admin',
        'ROLES_PERMISSIONS' => 'roles_permissions',
        'CUSTOMER' => 'customer',
        'VENDOR' => 'vendor',
        'REVIEW_RATING' => 'review_ratings',
        'MASTER' => 'master',
        'CATEGORY' => 'category',
        'SUB_CATEGORY' => 'sub_category',
        'STATE' => 'state',
        'CITY' => 'city',
        'JOB_SERVICE_REQUEST' => 'job_service_request',
        'OPEN_JOB' => 'open_jobs',
        'COMPLETED_JOB' => 'completed_jobs',
        'DISPUTE_JOB' => 'dispute_jobs',
        'REPORTS' => 'reports',
        'CONVERSION_REPORT' => 'conversion_report',
        'RATING_REPORT' => 'rating_report',
        'CONTACT_US' => 'contact_us',
        'SETTINGS' => 'settings',
        'MASTER_SETTING' => 'master_settings',
        'COMPANY' => 'company',
        'EMAIL' => 'email',
        'SMS' => 'sms',
        'SOCIAL_MEDIA' => 'social_media',
        'STATIC_PAGE' => 'static_page',
        'EMAIL_NOTIFICATION_BROADCAST_MESSAGE' => 'email_notification_broadcast_message',
        'EMAIL_TEMPLATE' => 'email_templates',
        'NOTIFICATION_TEMPLATE' => 'notification_template',
        'BROADCAST_MESSAGE' => 'broadcast_message',
        'COUNTRY'=>'country'
    ],
];
